name: sample-nextjs-inngest-app
services:
  - name: web
    environment_slug: node-js
    routes:
      - path: /
    github:
      repo: digitalocean/sample-inngest-app
      branch: main
      deploy_on_push: true
    build_command: "npm ci && npm run build"
    run_command: "npm run start"
    envs:
      # Required for Inngest client
      - key: INNGEST_APP_ID
        value: <REQUIRED>

      # Optional metadata
      - key: INNGEST_APP_NAME
        value: Next+Inngest DO App
      - key: INNGEST_ENV
        value: prod

      # Required if you call inngest.send() from the server
      - key: INNGEST_EVENT_KEY
        value: <REQUIRED>
        type: SECRET
        scope: RUN_TIME

      # Required for verifying signed requests from Inngest to /api/inngest
      - key: INNGEST_SIGNING_KEY
        value: <REQUIRED>
        type: SECRET
        scope: RUN_TIME

      # Recommended: pin Node version
      - key: NODE_VERSION
        value: "20"

      - key: NODE_ENV
        value: production
